/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const consola: typeof import('./global/consola')['consola']
  const debounce: typeof import('lodash-es')['debounce']
  const http: typeof import('./global/index')['http']
  const omit: typeof import('lodash-es')['omit']
}
